export { default as Header } from './header/Header';
export { default as Blog } from './blog/Blog';
export { default as Services } from './services/Services';
export { default as Possibility } from './possibility/Possibility';
export { default as Footer } from './footer/Footer';
export { default as Whatnpay } from './whatnpay/Whatnpay';
export { default as About } from './about/About';
export { default as Notdeveloper } from './notdeveloper/Notdeveloper';
export { default as Contact } from './contact/Contact';